service: mini-app-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  memorySize: 512
  versionFunctions: false
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN, ""}


resources:
  Resources:
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: TelegramPoCUserPool
        AliasAttributes:
          - email
        AutoVerifiedAttributes: []
        Schema:
          - Name: telegramId
            AttributeDataType: String
            Mutable: true
        MfaConfiguration: OFF

functions:
  postConfTrigger:
    handler: src/cognito.postConf

  preSignUpTrigger:
    handler: src/cognito.preSignUp
